(
 (c-mode
  (tab-width . 2)
  (c-basic-offset . 2)
  ;; (c-brace-offset . 0)
  (c-file-offsets
   (arglist-cont . 0)
   (arglist-intro . ++)
   (block-close . 0)
   (brace-list-intro . +)
   (case-label . +)
   (class-close . 0)
   (defun-block-intro . +)
   (defun-close . 0)
   (inclass . +)
   (member-init-cont . -)
   (member-init-intro . ++)
   (statement . 0)
   (statement-block-intro . +)
   (statement-case-intro . +)
   (statement-cont . ++)
   (topmost-intro . 0)
   (arglist-close . c-lineup-close-paren)
   (arglist-cont-nonempty . c-lineup-arglist)
   (c . c-lineup-C-comments)
   (comment-intro . c-lineup-comment)
   (cpp-macro . -1000)
   (inher-cont . c-lineup-multi-inher)
   (string . -1000)
   )
  (eval .
        (c-toggle-comment-style))
  )
 )

